AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener-backend

  Sample SAM Template for url-shortener-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128
    Timeout: 5
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  ShortenerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - http://localhost:5173
        AllowMethods: ['GET', 'POST', 'DELETE']
        AllowHeaders: ['Content-Type']
# dynamodb table
  ShortLinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ShortLinksTable
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
  
  # functions
  Create-Short-Link:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: create-link.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref ShortLinksTable
      Events:
        HttpPost:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref ShortenerApi
            Path: /links
            Method: POST
  RedirectLink:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: redirect.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ShortLinksTable
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShortenerApi
            Path: /{slug}
            Method: GET


  